remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Abhishek Yenpure
description: Ph.D. student in Computer Science. I am specializing in Scientific Visualization and High Performance Computing.